
package Vista;

import Modelo.Especialidades;
import Modelo.EspecialidadesDAO;
import Modelo.Login;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adm
 */
public class EspecialidadesG extends javax.swing.JFrame {

    Especialidades objEspecialidades = new  Especialidades();
    EspecialidadesDAO objEspecialidadesDAO = new EspecialidadesDAO();
     DefaultTableModel ModeloTabla = new DefaultTableModel();
   
    public EspecialidadesG() {
        initComponents();
        ListarEspecialidad();
        this.setLocationRelativeTo(null);
    }

    public void ListarEspecialidad(){
        
        List<Especialidades> objEspLista = objEspecialidadesDAO.ListarEspecialidad();
        ModeloTabla = (DefaultTableModel) TablaEspecialidad.getModel();
        Object[] obj = new Object[2];
        
        for(int i=0; i<objEspLista.size(); i++){
            
            obj[0] = objEspLista.get(i).getId();
            obj[1] = objEspLista.get(i).getDescripcion();
           
            ModeloTabla.addRow(obj);
            
        }//fin del for
         
        TablaEspecialidad.setModel(ModeloTabla);
        
    }//fin del metodo
 
     public void LimpiarTabla(){
        
        for(int i=0; i<ModeloTabla.getRowCount(); i++){
            
            ModeloTabla.removeRow(i);
           
            i = i+1;
            
        }//fin del for
        
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EspecialidadNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CrearEspecialidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEspecialidad = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        EspCodigo = new javax.swing.JTextField();
        EditarEspecialidad = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        EspecialidadNombre.setBackground(new java.awt.Color(255, 255, 255));
        EspecialidadNombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");

        CrearEspecialidad.setText("Crear");
        CrearEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEspecialidadActionPerformed(evt);
            }
        });

        TablaEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Especialidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEspecialidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEspecialidad);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Especialidad:");

        EspCodigo.setEditable(false);
        EspCodigo.setBackground(new java.awt.Color(255, 255, 255));
        EspCodigo.setForeground(new java.awt.Color(0, 0, 0));

        EditarEspecialidad.setText("Editar");
        EditarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEspecialidadActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("X");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CrearEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EspCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addComponent(EspecialidadNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EspCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EspecialidadNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CrearEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEspecialidadActionPerformed
        // TODO add your handling code here:
        
        if(!"".equals(EspecialidadNombre.getText())){
            objEspecialidades.setDescripcion(EspecialidadNombre.getText());
            
            objEspecialidadesDAO.RegistrarEspecialidad(objEspecialidades);
            
            JOptionPane.showMessageDialog(null,"Especialidad Registrada");
            
            
        }else{
            
             JOptionPane.showMessageDialog(null,"Debe llenar Todos los campos");
        }
        
    }//GEN-LAST:event_CrearEspecialidadActionPerformed

    private void TablaEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEspecialidadMouseClicked
        // TODO add your handling code here:
        int ValorTabla = TablaEspecialidad.rowAtPoint(evt.getPoint());

        EspCodigo.setText(TablaEspecialidad.getValueAt(ValorTabla, 0).toString());
        EspecialidadNombre.setText(TablaEspecialidad.getValueAt(ValorTabla, 1).toString());
     

    }//GEN-LAST:event_TablaEspecialidadMouseClicked

    private void EditarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEspecialidadActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(EspCodigo.getText())) {
            
            JOptionPane.showMessageDialog(null, "Debe Seleccionar una Especialidad");
            
            
        }//fin del if
        
        else{ 
            
            
            if(!"".equals(EspCodigo.getText()) && !"".equals(EspecialidadNombre.getText())  ){
                
                objEspecialidades.setDescripcion(EspecialidadNombre.getText());       
                objEspecialidades.setId(Integer.parseInt(EspCodigo.getText()));
                
             
                objEspecialidadesDAO.EditarEspecialidad(objEspecialidades);
                JOptionPane.showMessageDialog(null, "La especialidad ha sido Modificada");
            
           
            }//fin del if
            
            else{
                
                JOptionPane.showMessageDialog(null, "Hay campos vacios");
                
            }//fin del else
            
        }//fin del else
        
        
        
        
        
    }//GEN-LAST:event_EditarEspecialidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(EspecialidadesG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(EspecialidadesG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(EspecialidadesG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(EspecialidadesG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspecialidadesG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearEspecialidad;
    private javax.swing.JButton EditarEspecialidad;
    private javax.swing.JTextField EspCodigo;
    private javax.swing.JTextField EspecialidadNombre;
    private javax.swing.JTable TablaEspecialidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
