/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Login;
import java.awt.BorderLayout;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author adm
 */
public class MenuP extends javax.swing.JFrame {

    /**
     * Creates new form MenuP
     */
    
    
    
    //constructor por defecto
    public MenuP() {
      
        initComponents();
         BotonDoctor.setCursor(new Cursor(HAND_CURSOR));
        BotonPacientes.setCursor(new Cursor(HAND_CURSOR));
        BotonCitas.setCursor(new Cursor(HAND_CURSOR));
        BotonCerrar.setCursor(new Cursor(HAND_CURSOR)); 
        
    }
    
    
    
    //constructor  con sobrecarga de metodos
    
    public MenuP(Login Privilegios){
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //maximizo la ventana
     
        VerMedico me = new VerMedico ();
        me.setSize(1070, 550);
        me.setLocation(0, 0);
        
       
       
        
        if(Privilegios.getUsuarioTipo().equals("Usuario")){
            
            MenuCrearUsuario.setEnabled(false);
            MenuVerUsuario.setEnabled(false);
            
         
            NombreUsuario.setText("Bienvenido Usuario : "+Privilegios.getNombre());
            
            
        }else{
        
          NombreUsuario.setText("Bienvenido Administrador : "+Privilegios.getNombre());
           
            
    }
        
       
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        NombreUsuario = new javax.swing.JLabel();
        BotonDoctor = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();
        BotonPacientes = new javax.swing.JButton();
        Fondoazul2 = new javax.swing.JLabel();
        BotonCitas = new javax.swing.JButton();
        Fondoazul = new javax.swing.JLabel();
        Fondoazul3 = new javax.swing.JLabel();
        Fondoazul1 = new javax.swing.JLabel();
        Mostrar = new javax.swing.JLabel();
        FondoMenu = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuVer = new javax.swing.JMenu();
        MenuPaciente = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuMedicos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        MenuTurnos = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        MenuAdm = new javax.swing.JMenu();
        MenuSeg = new javax.swing.JMenu();
        MenuCrearUsuario = new javax.swing.JMenuItem();
        MenuVerUsuario = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        MenuAcercade = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1634, 982, -1, -1));

        NombreUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 990, 50));

        BotonDoctor.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        BotonDoctor.setForeground(new java.awt.Color(0, 0, 0));
        BotonDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NewdoctorGrande.png"))); // NOI18N
        BotonDoctor.setText("Médicos");
        BotonDoctor.setToolTipText("");
        BotonDoctor.setBorder(null);
        BotonDoctor.setContentAreaFilled(false);
        BotonDoctor.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newdoctorPe.png"))); // NOI18N
        BotonDoctor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicoNegroNew.png"))); // NOI18N
        BotonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 430, 310));

        BotonCerrar.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        BotonCerrar.setForeground(new java.awt.Color(0, 0, 0));
        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNEWWWGrande.png"))); // NOI18N
        BotonCerrar.setText("Cerrar Sesión");
        BotonCerrar.setToolTipText("");
        BotonCerrar.setBorder(null);
        BotonCerrar.setContentAreaFilled(false);
        BotonCerrar.setHideActionText(true);
        BotonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNEWWWpequena.png"))); // NOI18N
        BotonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salirNegroNewww.png"))); // NOI18N
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 430, 310));

        BotonPacientes.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        BotonPacientes.setForeground(new java.awt.Color(0, 0, 0));
        BotonPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PacienteNewGrande.png"))); // NOI18N
        BotonPacientes.setText("Pacientes");
        BotonPacientes.setToolTipText("");
        BotonPacientes.setBorder(null);
        BotonPacientes.setContentAreaFilled(false);
        BotonPacientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PacienteNewpequeno.png"))); // NOI18N
        BotonPacientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PacienteNewnegro.png"))); // NOI18N
        BotonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 430, 310));

        Fondoazul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoazulpanel.png"))); // NOI18N
        getContentPane().add(Fondoazul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 590, 330));

        BotonCitas.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        BotonCitas.setForeground(new java.awt.Color(0, 0, 0));
        BotonCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CitaGrandeNew.png"))); // NOI18N
        BotonCitas.setText("Citas");
        BotonCitas.setToolTipText("");
        BotonCitas.setBorder(null);
        BotonCitas.setContentAreaFilled(false);
        BotonCitas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CitaPequenaNew.png"))); // NOI18N
        BotonCitas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CitaGrandeNegroNew.png"))); // NOI18N
        BotonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCitasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 430, 310));

        Fondoazul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoazulpanel.png"))); // NOI18N
        getContentPane().add(Fondoazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 590, 330));

        Fondoazul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoazulpanel.png"))); // NOI18N
        getContentPane().add(Fondoazul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 590, 330));

        Fondoazul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoazulpanel.png"))); // NOI18N
        getContentPane().add(Fondoazul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 590, 330));

        Mostrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Mostrar.setForeground(new java.awt.Color(153, 153, 153));
        Mostrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MostrarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 170, 30));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoblancooo.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        MenuPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        MenuPrincipal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        MenuVer.setBackground(new java.awt.Color(204, 255, 255));
        MenuVer.setForeground(new java.awt.Color(0, 0, 0));
        MenuVer.setText("Ver");
        MenuVer.setAlignmentX(1.0F);
        MenuVer.setAlignmentY(1.0F);
        MenuVer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        MenuVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVerMouseClicked(evt);
            }
        });
        MenuVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerActionPerformed(evt);
            }
        });

        MenuPaciente.setText("Pacientes");
        MenuPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem4.setText("Registrar Paciente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItem4);

        jMenuItem5.setText("Ver Pacientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItem5);

        jMenuItem6.setText("Historial clinico");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        MenuPaciente.add(jMenuItem6);

        MenuVer.add(MenuPaciente);

        MenuMedicos.setText("Medicos");
        MenuMedicos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem1.setText("Registrar Medicos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuMedicos.add(jMenuItem1);

        jMenuItem2.setText("Ver Medicos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuMedicos.add(jMenuItem2);

        jMenuItem3.setText("Disponibilidad  de Medicos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuMedicos.add(jMenuItem3);

        jMenuItem8.setText("Especialidades de Medicos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MenuMedicos.add(jMenuItem8);

        MenuVer.add(MenuMedicos);

        MenuTurnos.setText("Citas");
        MenuTurnos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItem11.setText("Ver Citas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MenuTurnos.add(jMenuItem11);

        jMenuItem12.setText("Crear Nueva Cita");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MenuTurnos.add(jMenuItem12);

        jMenuItem13.setText("Editar Cita Existente");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MenuTurnos.add(jMenuItem13);

        MenuVer.add(MenuTurnos);

        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem10.setText("Salir del sistema");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MenuVer.add(jMenuItem10);

        MenuPrincipal.add(MenuVer);

        MenuAdm.setBackground(new java.awt.Color(204, 255, 255));
        MenuAdm.setForeground(new java.awt.Color(0, 0, 0));
        MenuAdm.setText("Administracion");
        MenuAdm.setAlignmentX(1.0F);
        MenuAdm.setAlignmentY(1.0F);
        MenuAdm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        MenuSeg.setText("Control & Seguridad");
        MenuSeg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        MenuCrearUsuario.setText("Crear usuario");
        MenuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearUsuarioActionPerformed(evt);
            }
        });
        MenuSeg.add(MenuCrearUsuario);

        MenuVerUsuario.setText("Ver Usuarios");
        MenuVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerUsuarioActionPerformed(evt);
            }
        });
        MenuSeg.add(MenuVerUsuario);

        jMenuItem9.setText("Cambiar Contraseña");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MenuSeg.add(jMenuItem9);

        MenuAdm.add(MenuSeg);

        MenuPrincipal.add(MenuAdm);

        MenuAcercade.setBackground(new java.awt.Color(204, 255, 255));
        MenuAcercade.setForeground(new java.awt.Color(0, 0, 0));
        MenuAcercade.setText("Ayuda");
        MenuAcercade.setAlignmentX(1.0F);
        MenuAcercade.setAlignmentY(1.0F);
        MenuAcercade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem7.setText("Acerca de");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MenuAcercade.add(jMenuItem7);

        MenuPrincipal.add(MenuAcercade);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
        
        
        
        
    private void MenuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearUsuarioActionPerformed
        // TODO add your handling code here:
         RegistroUsuario objRegistroUsuario = new RegistroUsuario();
         objRegistroUsuario.setVisible(true);
         dispose();
    }//GEN-LAST:event_MenuCrearUsuarioActionPerformed

    private void MenuVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerUsuarioActionPerformed
        VerUsuarios obj = new VerUsuarios();
        obj.setVisible(true);
        dispose();

        
    }//GEN-LAST:event_MenuVerUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   
        
        Medicos me = new Medicos ();
        me.setVisible(true);
      
       me.RMedicos();
        dispose();
           
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BotonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDoctorActionPerformed
         Medicos me = new Medicos();
           me.setVisible(true);
           dispose();
    }//GEN-LAST:event_BotonDoctorActionPerformed

    private void BotonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPacientesActionPerformed
        Paciente pa = new Paciente();
           pa.setVisible(true);
           
           
          dispose();
    }//GEN-LAST:event_BotonPacientesActionPerformed

    private void BotonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCitasActionPerformed
         Citas ci = new Citas();
           ci.setVisible(true);
           dispose();
    }//GEN-LAST:event_BotonCitasActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        LoginG objLoginG = new LoginG();
           objLoginG.setVisible(true);
           dispose();
    }//GEN-LAST:event_BotonCerrarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Acerca objAcercaP = new Acerca();
           objAcercaP.setVisible(true);
           
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Paciente Pa = new Paciente ();
        Pa.setVisible(true);
         
         Pa.RPaciente();
         dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        EspecialidadesG obj = new EspecialidadesG();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        CambiarClave obj = new CambiarClave();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
           dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void MenuVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVerActionPerformed

    private void MenuVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVerMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Medicos me = new Medicos ();
        me.setVisible(true);
      
       
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        Medicos me = new Medicos ();
        me.setVisible(true);
         
         me.DMedicos();
         dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Paciente Pa = new Paciente ();
        Pa.setVisible(true);
         
         Pa.VPaciente();
         dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Paciente Pa = new Paciente ();
        Pa.setVisible(true);
         
         Pa.HPaciente();
         dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
         Citas Ci = new Citas ();
        Ci.setVisible(true);
         
         Ci.VCitas();
         dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Citas Ci = new Citas ();
        Ci.setVisible(true);
         
         Ci.ACitas();
         dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void MostrarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MostrarAncestorAdded
        DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");

        
        Mostrar.setText( ""+dtf4.format(LocalDateTime.now()));
               
    }//GEN-LAST:event_MostrarAncestorAdded

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         Citas Ci = new Citas ();
        Ci.setVisible(true);
         
         Ci.ACitas();
         dispose();
        
        
  
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonCitas;
    private javax.swing.JButton BotonDoctor;
    private javax.swing.JButton BotonPacientes;
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JLabel Fondoazul;
    private javax.swing.JLabel Fondoazul1;
    private javax.swing.JLabel Fondoazul2;
    private javax.swing.JLabel Fondoazul3;
    private javax.swing.JMenu MenuAcercade;
    private javax.swing.JMenu MenuAdm;
    private javax.swing.JMenuItem MenuCrearUsuario;
    private javax.swing.JMenu MenuMedicos;
    private javax.swing.JMenu MenuPaciente;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuSeg;
    private javax.swing.JMenu MenuTurnos;
    private javax.swing.JMenu MenuVer;
    private javax.swing.JMenuItem MenuVerUsuario;
    private javax.swing.JLabel Mostrar;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
