/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;


import Modelo.Medicos;
import Modelo.MedicoDAO;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import javax.swing.JOptionPane;


/**
 *
 * @author Matias
 */
public class RegistrarMedico extends javax.swing.JPanel {

   Medicos objMedico = new Medicos();
   MedicoDAO objMedicoDAO = new MedicoDAO();
    
    
    /**
     * Creates new form Medico
     */
    public RegistrarMedico() {
        initComponents();
       
        
       // AutoCompleteDecorator.decorate(CbxProductoSuplidor);
        objMedicoDAO.ConsultarEspecialidad(EspecialidadMedico);
        BotonRegistrar.setCursor(new Cursor(HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        NombreMedico1 = new javax.swing.JLabel();
        NombreMedico2 = new javax.swing.JLabel();
        NombreMedico3 = new javax.swing.JLabel();
        NombreMedico4 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        NombreMedico6 = new javax.swing.JLabel();
        NombreMedico7 = new javax.swing.JLabel();
        ApellidoMedico = new javax.swing.JTextField();
        TelefonoMedico = new javax.swing.JTextField();
        NombreMedico = new javax.swing.JTextField();
        DomicilioMedico = new javax.swing.JTextField();
        NombreMedico8 = new javax.swing.JLabel();
        CedulaMedico = new javax.swing.JTextField();
        BotonRegistrar = new javax.swing.JButton();
        JornadaMedico = new javax.swing.JComboBox<>();
        EspecialidadMedico = new javax.swing.JComboBox<>();
        EstadoMedico = new javax.swing.JComboBox<>();
        SexoMedico = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 550));

        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre : ");

        NombreMedico1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico1.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico1.setText("Especialidad : ");
        NombreMedico1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NombreMedico1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreMedico1MouseClicked(evt);
            }
        });

        NombreMedico2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico2.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico2.setText("Teléfono :");

        NombreMedico3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico3.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico3.setText("Domicilio :");

        NombreMedico4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico4.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico4.setText("Sexo:");

        Apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setText("Apellido :");

        NombreMedico6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico6.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico6.setText("Cédula :");

        NombreMedico7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico7.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico7.setText("Estado civil :");

        NombreMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreMedicoActionPerformed(evt);
            }
        });

        NombreMedico8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico8.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico8.setText("Jornada :");

        BotonRegistrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BotonRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        BotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarGrande.png"))); // NOI18N
        BotonRegistrar.setContentAreaFilled(false);
        BotonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarP.png"))); // NOI18N
        BotonRegistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarGrande.png"))); // NOI18N
        BotonRegistrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseExited(evt);
            }
        });
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        JornadaMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Matutina", "Vespertina", "Noctura" }));

        EstadoMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Casado", "Soltero" }));

        SexoMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApellidoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EspecialidadMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico8)
                            .addComponent(NombreMedico4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(NombreMedico6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreMedico7))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Apellido)
                                    .addGap(292, 292, 292)
                                    .addComponent(NombreMedico3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(NombreMedico2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TelefonoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SexoMedico, 0, 273, Short.MAX_VALUE)
                            .addComponent(JornadaMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EstadoMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DomicilioMedico)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspecialidadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DomicilioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreMedico8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JornadaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreMedicoActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
        
              
    if (!"".equals(CedulaMedico.getText()) && !"".equals(NombreMedico.getText()) && !"".equals(TelefonoMedico.getText()) && !"".equals(DomicilioMedico.getText()) && !"".equals(EstadoMedico.getSelectedItem()) && !"".equals(SexoMedico.getSelectedItem()) && !"".equals(JornadaMedico.getSelectedItem()) && !"".equals(EspecialidadMedico.getSelectedItem()) ) {

       
        objMedico.setCedula(CedulaMedico.getText());
        objMedico.setNombre(NombreMedico.getText());
        objMedico.setApellido(ApellidoMedico.getText());
        objMedico.setTelefono(TelefonoMedico.getText());
        objMedico.setDomicilio(DomicilioMedico.getText());
        objMedico.setEstado((String) EstadoMedico.getSelectedItem());
        objMedico.setSexo((String) SexoMedico.getSelectedItem());
        objMedico.setJornada((String) JornadaMedico.getSelectedItem());
        objMedico.setEspecialidad((String) EspecialidadMedico.getSelectedItem());
      
       objMedicoDAO.RegistrarMedico(objMedico);
       
            JOptionPane.showMessageDialog(null, "Los Datos del Medico han sido guardado de manera correcta");

        }//fin del if
        else {

            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los campos");
        }//fin del else
        
        
        
        
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void NombreMedico1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreMedico1MouseClicked
      
        
    }//GEN-LAST:event_NombreMedico1MouseClicked

    private void BotonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseExited
         BotonRegistrar.setText("");
    }//GEN-LAST:event_BotonRegistrarMouseExited

    private void BotonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseEntered
       BotonRegistrar.setText("Guardar");
    }//GEN-LAST:event_BotonRegistrarMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoMedico;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JTextField CedulaMedico;
    private javax.swing.JTextField DomicilioMedico;
    private javax.swing.JComboBox<String> EspecialidadMedico;
    private javax.swing.JComboBox<String> EstadoMedico;
    private javax.swing.JComboBox<String> JornadaMedico;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreMedico;
    private javax.swing.JLabel NombreMedico1;
    private javax.swing.JLabel NombreMedico2;
    private javax.swing.JLabel NombreMedico3;
    private javax.swing.JLabel NombreMedico4;
    private javax.swing.JLabel NombreMedico6;
    private javax.swing.JLabel NombreMedico7;
    private javax.swing.JLabel NombreMedico8;
    private javax.swing.JComboBox<String> SexoMedico;
    private javax.swing.JTextField TelefonoMedico;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
