/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Paciente;
import Modelo.PacienteDAO;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author Matias
 */
public class RegistrarPaciente extends javax.swing.JPanel {
    
    Paciente objPaciente = new Paciente();
    PacienteDAO objPacienteDAO = new PacienteDAO();
    
    

    /**
     * Creates new form Medico
     */
    public RegistrarPaciente() {
        initComponents();
        
        BotonRegistrar.setCursor(new Cursor(HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        NombreMedico2 = new javax.swing.JLabel();
        NombreMedico3 = new javax.swing.JLabel();
        NombreMedico4 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        NombreMedico6 = new javax.swing.JLabel();
        NombreMedico7 = new javax.swing.JLabel();
        ApellidoPaciente = new javax.swing.JTextField();
        TelefonoPaciente = new javax.swing.JTextField();
        NombrePaciente = new javax.swing.JTextField();
        DomicilioPaciente = new javax.swing.JTextField();
        NombreMedico8 = new javax.swing.JLabel();
        CedulaPaciente = new javax.swing.JTextField();
        NombreMedico10 = new javax.swing.JLabel();
        NombreMedico5 = new javax.swing.JLabel();
        EdadPaciente = new javax.swing.JTextField();
        BotonRegistrar = new javax.swing.JButton();
        CbxPacienteEstado = new javax.swing.JComboBox<>();
        CbxPacienteSexo = new javax.swing.JComboBox<>();
        JdtPacienteNacimiento = new com.toedter.calendar.JDateChooser();
        JdtPacienteFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 550));

        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre : ");

        NombreMedico2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico2.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico2.setText("Cédula :");

        NombreMedico3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico3.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico3.setText("Domicilio :");

        NombreMedico4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico4.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico4.setText("Sexo:");

        Apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setText("Apellido :");

        NombreMedico6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico6.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico6.setText("Teléfono :");

        NombreMedico7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico7.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico7.setText("Estado civil :");

        NombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePacienteActionPerformed(evt);
            }
        });

        DomicilioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomicilioPacienteActionPerformed(evt);
            }
        });

        NombreMedico8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico8.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico8.setText("Fecha de ingreso : ");

        NombreMedico10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico10.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico10.setText("Fecha de nacimiento:");

        NombreMedico5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico5.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico5.setText("Edad :");

        EdadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadPacienteActionPerformed(evt);
            }
        });

        BotonRegistrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BotonRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        BotonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarGrande.png"))); // NOI18N
        BotonRegistrar.setContentAreaFilled(false);
        BotonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarP.png"))); // NOI18N
        BotonRegistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarGrande.png"))); // NOI18N
        BotonRegistrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseExited(evt);
            }
        });
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        CbxPacienteEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero/a", "Casado/a", "Viudo/a", "Divorciado/a" }));

        CbxPacienteSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Masculino", "Femenino" }));

        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarG.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setHideActionText(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarP.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarG.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarG.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarP.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarG.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 38, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NombreMedico2)
                                    .addComponent(NombreMedico6)
                                    .addComponent(NombreMedico3)
                                    .addComponent(Apellido))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DomicilioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(NombreMedico8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NombreMedico5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(NombreMedico7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(NombreMedico4, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(NombreMedico10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JdtPacienteFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EdadPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(CbxPacienteEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CbxPacienteSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JdtPacienteNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JdtPacienteNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreMedico10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxPacienteEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbxPacienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreMedico8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JdtPacienteFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DomicilioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePacienteActionPerformed

    private void DomicilioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomicilioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DomicilioPacienteActionPerformed

    private void EdadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadPacienteActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
        
       //convierto las fechas
       int Anac,Aing;
       int Mnac,Ming;
       int Dnac,Ding;
       
       
       Anac = JdtPacienteNacimiento.getCalendar().get(Calendar.YEAR);
       Aing = JdtPacienteFecha.getCalendar().get(Calendar.YEAR);
       Mnac = JdtPacienteNacimiento.getCalendar().get(Calendar.MONTH)+1;
       Ming = JdtPacienteFecha.getCalendar().get(Calendar.MONTH)+1;
       Dnac = JdtPacienteNacimiento.getCalendar().get(Calendar.DAY_OF_MONTH);
       Ding = JdtPacienteFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
       
       String NfechaNac = Anac+ "-"+Mnac+ "-"+Dnac;
       String NfechaIng = Aing+ "-"+Ming+ "-"+Ding;
       
       //fin convertir fechas
        
    if (!"".equals(CedulaPaciente.getText()) && !"".equals(NombrePaciente.getText()) && !"".equals(TelefonoPaciente.getText()) && !"".equals(DomicilioPaciente.getText()) && !"".equals(JdtPacienteNacimiento.getDate()) && !"".equals(EdadPaciente.getText()) && !"".equals(CbxPacienteEstado.getSelectedItem()) && !"".equals(CbxPacienteSexo.getSelectedItem()) && !"".equals(JdtPacienteFecha.getDate()) ) {

        objPaciente.setCedula(CedulaPaciente.getText());
        objPaciente.setNombre(NombrePaciente.getText());
        objPaciente.setApellido(ApellidoPaciente.getText());
        objPaciente.setTelefono(TelefonoPaciente.getText());
        objPaciente.setDireccion(DomicilioPaciente.getText());
        objPaciente.setFechaNacimiento(NfechaNac);
        objPaciente.setEdad(Integer.parseInt(EdadPaciente.getText()));
        objPaciente.setEstado((String) CbxPacienteEstado.getSelectedItem());
        objPaciente.setSexo((String) CbxPacienteSexo.getSelectedItem());
       objPaciente.setFechaIngreso(NfechaIng);
      
       objPacienteDAO.RegistrarPaciente(objPaciente);
              
            JOptionPane.showMessageDialog(null, "Los datos del paciente han sido guardado de manera correcta");

        }//fin del if
        else {

            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los campos");
        }//fin del else

        
        
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseExited
       BotonRegistrar.setText("");
    }//GEN-LAST:event_BotonRegistrarMouseExited

    private void BotonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseEntered
        BotonRegistrar.setText("Guardar");
    }//GEN-LAST:event_BotonRegistrarMouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setText("Buscar Cita");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setText("");
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setText("Editar Cambios");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setText("");
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

      /*  int Afecha;
        int Mfecha;
        int Dfecha;

        Afecha = FechaCita.getCalendar().get(Calendar.YEAR);
        Mfecha = FechaCita.getCalendar().get(Calendar.MONTH)+1;
        Dfecha = FechaCita.getCalendar().get(Calendar.DAY_OF_MONTH);

        String NfechaCita = Afecha+ "-"+Mfecha+ "-"+Dfecha;

        if(!"".equals(IdCita.getText()) || !"".equals( TxtNombre.getText()) || !"".equals(TxtApellido.
            getText()) || !"".equals(TxtCedula.getText())  || !"".equals(TxtTelefono.getText()) || !"".equals(TxtEdad.getText()) || !"".equals(CbxSexo.
            getSelectedIndex()) || !"".equals(FechaCita.getDate()) || !"".equals(CbxJornada.getSelectedIndex())   || !"".equals(TxtHora.
            getText()) || !"".equals(CbxMedico.getSelectedIndex()) || !"".equals(CbxCita.getSelectedIndex())){

        objCita.setNombre(TxtNombre.getText());
        objCita.setApellido(TxtApellido.getText());
        objCita.setCedula(TxtCedula.getText());
        objCita.setTelefono(TxtTelefono.getText());
        objCita.setEdad(Integer.parseInt(TxtEdad.getText()));
        objCita.setSexo(CbxSexo.getSelectedItem().toString());
        objCita.setFecha(NfechaCita);
        objCita.setJornada(CbxJornada.getSelectedItem().toString());
        objCita.setHora(TxtHora.getText());
        objCita.setTipo(CbxCita.getSelectedItem().toString());
        objCita.setMedico(CbxMedico.getSelectedItem().toString());

        objCitaDAO.ModificarCita(objCita);
        JOptionPane.showMessageDialog(null, "La cita fue cambiada");

        }//fin del if

        else{

            JOptionPane.showMessageDialog(null, "Hay campos vacios");

        }//fin del else*/

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoPaciente;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JComboBox<String> CbxPacienteEstado;
    private javax.swing.JComboBox<String> CbxPacienteSexo;
    private javax.swing.JTextField CedulaPaciente;
    private javax.swing.JTextField DomicilioPaciente;
    private javax.swing.JTextField EdadPaciente;
    private com.toedter.calendar.JDateChooser JdtPacienteFecha;
    private com.toedter.calendar.JDateChooser JdtPacienteNacimiento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreMedico10;
    private javax.swing.JLabel NombreMedico2;
    private javax.swing.JLabel NombreMedico3;
    private javax.swing.JLabel NombreMedico4;
    private javax.swing.JLabel NombreMedico5;
    private javax.swing.JLabel NombreMedico6;
    private javax.swing.JLabel NombreMedico7;
    private javax.swing.JLabel NombreMedico8;
    private javax.swing.JTextField NombrePaciente;
    private javax.swing.JTextField TelefonoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
