/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Matias
 */
public class RegistrarPaciente extends javax.swing.JPanel {

    /**
     * Creates new form Medico
     */
    public RegistrarPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        NombreMedico2 = new javax.swing.JLabel();
        NombreMedico3 = new javax.swing.JLabel();
        NombreMedico4 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        NombreMedico6 = new javax.swing.JLabel();
        NombreMedico7 = new javax.swing.JLabel();
        ApellidoPaciente = new javax.swing.JTextField();
        TelefonoPaciente = new javax.swing.JTextField();
        NombrePaciente = new javax.swing.JTextField();
        IngresoPaciente = new javax.swing.JTextField();
        EstadoPaciente = new javax.swing.JTextField();
        DomicilioPaciente = new javax.swing.JTextField();
        SexoPaciente = new javax.swing.JTextField();
        NombreMedico8 = new javax.swing.JLabel();
        CedulaPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NombreMedico9 = new javax.swing.JLabel();
        HorarioPaciente = new javax.swing.JTextField();
        NombreMedico10 = new javax.swing.JLabel();
        NacimientoPaciente = new javax.swing.JTextField();
        NombreMedico5 = new javax.swing.JLabel();
        EdadPaciente = new javax.swing.JTextField();
        BotonRegistrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 550));

        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre : ");

        NombreMedico2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico2.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico2.setText("Cédula :");

        NombreMedico3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico3.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico3.setText("Domicilio :");

        NombreMedico4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico4.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico4.setText("Sexo:");

        Apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setText("Apellido :");

        NombreMedico6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico6.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico6.setText("Teléfono :");

        NombreMedico7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico7.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico7.setText("Estado civil :");

        NombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePacienteActionPerformed(evt);
            }
        });

        DomicilioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomicilioPacienteActionPerformed(evt);
            }
        });

        NombreMedico8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico8.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico8.setText("Fecha de ingreso : ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PacienteReg.png"))); // NOI18N

        NombreMedico9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico9.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico9.setText("Hora de ingreso : ");

        NombreMedico10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico10.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico10.setText("Fecha de nacimiento:");

        NacimientoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NacimientoPacienteActionPerformed(evt);
            }
        });

        NombreMedico5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreMedico5.setForeground(new java.awt.Color(0, 0, 0));
        NombreMedico5.setText("Edad :");

        EdadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadPacienteActionPerformed(evt);
            }
        });

        BotonRegistrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BotonRegistrar.setForeground(new java.awt.Color(51, 51, 51));
        BotonRegistrar.setText("Registrar ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NombreMedico6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreMedico8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico10)
                            .addComponent(NombreMedico3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorarioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NacimientoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DomicilioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreMedico3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DomicilioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NacimientoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreMedico10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreMedico5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 19, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 19, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(NombreMedico7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EstadoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreMedico4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TelefonoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IngresoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreMedico8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreMedico9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorarioPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonRegistrar)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePacienteActionPerformed

    private void DomicilioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomicilioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DomicilioPacienteActionPerformed

    private void NacimientoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NacimientoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NacimientoPacienteActionPerformed

    private void EdadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField ApellidoPaciente;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JTextField CedulaPaciente;
    private javax.swing.JTextField DomicilioPaciente;
    private javax.swing.JTextField EdadPaciente;
    private javax.swing.JTextField EstadoPaciente;
    private javax.swing.JTextField HorarioPaciente;
    private javax.swing.JTextField IngresoPaciente;
    private javax.swing.JTextField NacimientoPaciente;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreMedico10;
    private javax.swing.JLabel NombreMedico2;
    private javax.swing.JLabel NombreMedico3;
    private javax.swing.JLabel NombreMedico4;
    private javax.swing.JLabel NombreMedico5;
    private javax.swing.JLabel NombreMedico6;
    private javax.swing.JLabel NombreMedico7;
    private javax.swing.JLabel NombreMedico8;
    private javax.swing.JLabel NombreMedico9;
    private javax.swing.JTextField NombrePaciente;
    private javax.swing.JTextField SexoPaciente;
    private javax.swing.JTextField TelefonoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
