/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Login;
import Modelo.LoginDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Acerca
     */
    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        xxx1 = new javax.swing.JLabel();
        FondoPortada = new javax.swing.JLabel();
        NombreRegristro = new javax.swing.JLabel();
        NombreRegristro2 = new javax.swing.JLabel();
        UsuarioRegristro = new javax.swing.JLabel();
        NombreRegristro3 = new javax.swing.JLabel();
        xxx = new javax.swing.JLabel();
        TxtUsuarioUser = new javax.swing.JTextField();
        TxtUsuarioNombre = new javax.swing.JTextField();
        TxtUsuarioNuevaPassword = new javax.swing.JPasswordField();
        BtnUsuarioRegistrar = new javax.swing.JButton();
        TxtUsuarioPassword = new javax.swing.JPasswordField();
        CbxUsuarioTipo = new javax.swing.JComboBox<>();
        NombreRegristro4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("X");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 50, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("-");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 50, 30));

        xxx1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        xxx1.setForeground(new java.awt.Color(204, 255, 255));
        xxx1.setText("Registro Usuario");
        jPanel1.add(xxx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        FondoPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Portada.jpg"))); // NOI18N
        jPanel1.add(FondoPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 700));

        NombreRegristro.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NombreRegristro.setForeground(new java.awt.Color(0, 0, 0));
        NombreRegristro.setText("Nombre: ");
        jPanel1.add(NombreRegristro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        NombreRegristro2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NombreRegristro2.setForeground(new java.awt.Color(0, 0, 0));
        NombreRegristro2.setText("Tipo de usuario:");
        jPanel1.add(NombreRegristro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 120, -1));

        UsuarioRegristro.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        UsuarioRegristro.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioRegristro.setText("Usuario :");
        jPanel1.add(UsuarioRegristro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        NombreRegristro3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NombreRegristro3.setForeground(new java.awt.Color(0, 0, 0));
        NombreRegristro3.setText("Contraseña : ");
        jPanel1.add(NombreRegristro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        xxx.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        xxx.setForeground(new java.awt.Color(0, 0, 0));
        xxx.setText("Registro Usuario");
        jPanel1.add(xxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 310, -1));

        TxtUsuarioUser.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuarioUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TxtUsuarioUser.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsuarioUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioUserActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 220, -1));

        TxtUsuarioNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuarioNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TxtUsuarioNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsuarioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsuarioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, 220, -1));

        TxtUsuarioNuevaPassword.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuarioNuevaPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtUsuarioNuevaPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TxtUsuarioNuevaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 220, -1));

        BtnUsuarioRegistrar.setText("Registrar");
        BtnUsuarioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUsuarioRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 170, 50));

        TxtUsuarioPassword.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuarioPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtUsuarioPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(TxtUsuarioPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 220, -1));

        CbxUsuarioTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Usuario" }));
        jPanel1.add(CbxUsuarioTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, 130, 30));

        NombreRegristro4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        NombreRegristro4.setForeground(new java.awt.Color(0, 0, 0));
        NombreRegristro4.setText("Confirmar Contraseña: ");
        jPanel1.add(NombreRegristro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 160, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondoblancooo.jpg"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        jLabel1.setRequestFocusEnabled(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1120, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MenuP MP = new MenuP();
           MP.setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtUsuarioUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioUserActionPerformed

    private void TxtUsuarioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioNombreActionPerformed

    private void BtnUsuarioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioRegistrarActionPerformed
        // TODO add your handling code here:

        Login objLogin = new Login();
        LoginDAO objLoginDao = new LoginDAO();

        String pass = new String(TxtUsuarioPassword.getPassword()); //obtengo contraseña
        String passCon = new String(TxtUsuarioNuevaPassword.getPassword());//obtengo confirmacion de contraseña

        //valido que no hayan campos vacios
        if(TxtUsuarioNombre.getText().equals(" ") ||pass.equals(" ")|| passCon.equals(" ") || TxtUsuarioUser.getText().equals("") ||CbxUsuarioTipo.getSelectedItem().equals(" ")){

            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los campos");

        }//fin if validar campos vacios
        else{

            if(pass.equals(passCon)){

                objLogin.setNombre(TxtUsuarioNombre.getText());
                objLogin.setUser(TxtUsuarioUser.getText());
                objLogin.setClave(TxtUsuarioPassword.getText());
                objLogin.setUsuarioTipo(CbxUsuarioTipo.getSelectedItem().toString());

                objLoginDao.RegistrarUsuario(objLogin);

                JOptionPane.showMessageDialog(null, "El usuario ha sido Registrado");

            }//fin if validar password

            else{
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }//fin else validar password

        }//fin else validar campos vacios

    }//GEN-LAST:event_BtnUsuarioRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUsuarioRegistrar;
    private javax.swing.JComboBox<String> CbxUsuarioTipo;
    private javax.swing.JLabel FondoPortada;
    private javax.swing.JLabel NombreRegristro;
    private javax.swing.JLabel NombreRegristro2;
    private javax.swing.JLabel NombreRegristro3;
    private javax.swing.JLabel NombreRegristro4;
    private javax.swing.JTextField TxtUsuarioNombre;
    private javax.swing.JPasswordField TxtUsuarioNuevaPassword;
    private javax.swing.JPasswordField TxtUsuarioPassword;
    private javax.swing.JTextField TxtUsuarioUser;
    private javax.swing.JLabel UsuarioRegristro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel xxx;
    private javax.swing.JLabel xxx1;
    // End of variables declaration//GEN-END:variables
}
