/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

 import Modelo.Login;
import Modelo.LoginDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author adm
 */
public class VerUsuarios extends javax.swing.JFrame {

    LoginDAO objLoginDAO = new LoginDAO();
    Login objLogin = new Login();
    DefaultTableModel ModeloTabla = new DefaultTableModel();
    TableRowSorter TrsBuscar;
    
    /**
     * Creates new form VerUsuarios
     */
    public VerUsuarios() {
        initComponents();
        ListarUsuario();
        
        
        this.setLocationRelativeTo(null);
    }
    
    public void ListarUsuario(){
        
        List<Login> objLoginLista = objLoginDAO.ListarUsuario();
        ModeloTabla = (DefaultTableModel) TablaUsuario.getModel();
        Object[] obj = new Object[4];
        
        for(int i=0; i<objLoginLista.size(); i++){
            
            obj[0] = objLoginLista.get(i).getId();
            obj[1] = objLoginLista.get(i).getNombre();
            obj[2] = objLoginLista.get(i).getUser();
            obj[3] = objLoginLista.get(i).getUsuarioTipo();
          
            
            ModeloTabla.addRow(obj);
            
        }//fin del for
         
        TablaUsuario.setModel(ModeloTabla);
        
    }//fin del metodo
 
     public void LimpiarTabla(){
        
        for(int i=0; i<ModeloTabla.getRowCount(); i++){
            
            ModeloTabla.removeRow(i);
           
            i = i+1;
            
        }//fin del for
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuario = new javax.swing.JTable();
        NombreU = new javax.swing.JTextField();
        UsuarioU = new javax.swing.JTextField();
        TipoUsuarioU = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CodigoU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(3840, 2160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaUsuario.setBackground(new java.awt.Color(204, 204, 204));
        TablaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        TablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Usuario", "Tipo de Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        TablaUsuario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 710, 530));
        jPanel1.add(NombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 145, -1));
        jPanel1.add(UsuarioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 145, -1));

        TipoUsuarioU.setEditable(true);
        TipoUsuarioU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Usuario" }));
        TipoUsuarioU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUsuarioUActionPerformed(evt);
            }
        });
        jPanel1.add(TipoUsuarioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 145, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 53, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 50, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 77, -1));

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 70, 30));

        jButton4.setText("Cambiar Contraseña");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 130, 30));

        CodigoU.setEditable(false);
        jPanel1.add(CodigoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 140, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 50, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Buscar Usuario :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jButton5.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 204, 204));
        jButton5.setText("_");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 50, 40));

        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setText("X");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 0, 1080, 681));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Ver Usuarios");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Portada.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuarioMouseClicked
        // TODO add your handling code here:
         int ValorTabla = TablaUsuario.rowAtPoint(evt.getPoint());
        
       CodigoU.setText(TablaUsuario.getValueAt(ValorTabla, 0).toString());
        NombreU.setText(TablaUsuario.getValueAt(ValorTabla, 1).toString());
        UsuarioU.setText(TablaUsuario.getValueAt(ValorTabla, 2).toString());
       TipoUsuarioU.setSelectedItem(TablaUsuario.getValueAt(ValorTabla, 3).toString());
        
        
    }//GEN-LAST:event_TablaUsuarioMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(CodigoU.getText())) {
            
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un Usuario");
            
            
        }//fin del if
        
        else{ 
            
            
            if(!"".equals(CodigoU.getText()) && !"".equals(NombreU.getText()) && !"".equals(TipoUsuarioU.getSelectedIndex()) && !"".equals(UsuarioU.getText()) ){
                
                objLogin.setNombre(NombreU.getText());
                objLogin.setUser(UsuarioU.getText());
                objLogin.setUsuarioTipo(TipoUsuarioU.getSelectedItem().toString());          
                objLogin.setId(Integer.parseInt(CodigoU.getText()));
                
             
                objLoginDAO.ModificarUsuario(objLogin);
                JOptionPane.showMessageDialog(null, "El ususario ha sido Modificado");
            
           
            }//fin del if
            
            else{
                
                JOptionPane.showMessageDialog(null, "Hay campos vacios");
                
            }//fin del else
            
        }//fin del else
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        CambiarClave obj = new CambiarClave();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyTyped
        // TODO add your handling code here:
        
        TxtBuscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
              
              TrsBuscar.setRowFilter(RowFilter.regexFilter(TxtBuscar.getText(), 0,1));
                
                
            }
            
        } );
        
        
        TrsBuscar = new TableRowSorter(ModeloTabla);
        TablaUsuario.setRowSorter(TrsBuscar);
        
        
        
        
    }//GEN-LAST:event_TxtBuscarKeyTyped

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void TipoUsuarioUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUsuarioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUsuarioUActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        MenuP MP = new MenuP();
           MP.setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VerUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoU;
    private javax.swing.JTextField NombreU;
    private javax.swing.JTable TablaUsuario;
    private javax.swing.JComboBox<String> TipoUsuarioU;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField UsuarioU;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
